development:
  secret_key_base: "execute 'rake secrets' to generate new key"
 
test:
  secret_key_base: "execute 'rake secrets' to generate new key"
 
production:
  secret_key_base:
    secret_token: "execute 'rake secrets' to generate new key"
          